# Generated by Django 5.1.3 on 2024-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Cookies', 'COOKIES'), ('Bread', 'BREAD'), ('Pastries', 'PASTRIES'), ('Cakes', 'CAKES'), ('Savory Items', 'SAVORY ITEMS'), ('Drinks', 'DRINKS'), ('Indian Savory Snacks', 'INDIAN SAVORY SNACKS'), ('Festive and Seasonal Items', 'FESTIVE AND SEASONAL'), ('Roasted Items', 'ROASTED ITEMS'), ('Ready to Eat', 'Ready-to-Eat')], max_length=40, null=True),
        ),
    ]
